baseURL = 'http://localhost:8000/'
publishDir = "public_dev"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
# Build EN, NL and RO locally; all other languages disabled to keep dev fast
disableLanguages = [
# Uncomment next line to disable fr language in dev mode
# "fr", 
# Uncomment next line to disable NL language in dev mode
#  "nl",
  # The rest of the languages are disabled in dev mode
  "sk","ur","zh-hans","zh-hant","sw","kab","ug","pl","sq","sv","he","ms","da","mr","gu","mn","mi","pt_br","ja","el","lv","it","ca","cs","te","pt_pt","ru","tl","nqo","km_kh","uk","sr","pa","si","ku","mk","ba","my","ar","gl","hr","hu","bg","bn","ne","fil","af","nb","hi","ka","de","az","ko","fi","id","ro","es","et","fa","lt","eu","jv","ta","tr"
]

[server]
  renderToDisk = false