name: ğŸ§ª End To End (e2e) Tests Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ§± Hugo build
        uses: jakejarvis/hugo-build-action@master 
        with:
          args: --gc --config ./config.toml -b http://localhost:1313
      - name: ğŸ•¸ï¸ Run server
        run: |
          cd public && python -m http.server 1313 &
      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: ğŸ‘¨â€ğŸ‘©â€ğŸ‘§ Install dependencies
        working-directory: ./test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ğŸ§­ Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: ğŸ§ª Run your tests
        working-directory: ./test
        run: pytest --base-url http://localhost:1313 -v --junitxml report.xml e2e/*
      - name: ğŸ“· Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: test/screenshots/
      - name: ğŸ“– Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Tests
          path: './test/report.xml'
          reporter: java-junit
