# This workflow scrapes the latest show episodes and commits the new episode and data
# files to the repo.

name: 'ğŸ§¹ Sanitize commercial support links and commit'
on:
  schedule:
    - cron: '0 0 * * 0'  # At midnight UTC every Sunday
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'qgis'
    steps:
    - name: 'ğŸ›’ Checkout QGIS Website'
      uses: actions/checkout@v5
      with:
        ref: main
        path: ./qgis-website

    - name: 'ğŸ Setup Python'
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: "pipenv"

    - name: 'ğŸš¸Install Python deps'
      run: |
        cd ./qgis-website
        pip install pipenv && pipenv install -r REQUIREMENTS.txt && pipenv sync --bare
        pipenv run pip freeze

    - name: 'âš™ï¸ Check commercial support links'
      run: |
        cd ./qgis-website
        pipenv run ./scripts/sanitize_commercial_supports.py

    - name: 'âœ‰ï¸ Commit'
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: 'Commercial support links sanitized and committed via a GitHub Action.'
        repository: ./qgis-website
        # push_options: --force
